### ISSUE TITLE
Missing & SSH-based dependency submodules

### ISSUE THREAD

**Issue by 20kdc** [janusvr/janus#31]
The submodules in .gitmodules use the form: `git@github.com:panmarco83/openal-soft.git`

Of these, all of them use the SSH form (which seems to require logging in with a public key?), one (assimp's) has an additional `/` at the end (which appears to cause some weird problem I don't understand), and finally, `assimp` and `openvr` are not existing or not publically accessible repositories.

**Comment by 20kdc** [comment]
Note that replacing `assimp` with the official version *does not work*, as it results in:
```
In file included from resources/assimp-5.0.1/include/assimp/types.h:59,
                 from resources/assimp-5.0.1/include/assimp/Importer.hpp:56,
                 from src/geom.h:7,
                 from src/assetobject.h:10,
                 from src/assetobject.cpp:1:
resources/assimp-5.0.1/include/assimp/defs.h:53:10: fatal error: assimp/config.h: No such file or directory
   53 | #include <assimp/config.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:7922: assetobject.o] Error 1
```
For now my workaround is to copy that file back, but this all seems broken.
Fixing it specifically for Linux is probably easy enough but that would break the Windows MSVC build, unless more drastic measures were taken.
(A suggestion: Godot-style "just plain force all dependencies that aren't stdlib/qt to conform with a unified build standard" where that standard is QMake would mean that regardless of OS, "load it in Qt Creator" is a valid solution)

**Comment by 20kdc** [comment]
Addendum to previous issue comment:
The Notes So Far:
+ Replacing submodules with the upstream URLs "kinda worked". I suspect the issues after this are NOT because of that.
+ OpenVR's submodule path doesn't match the include path for it.
+ Some of this MIGHT be due to the build\_dir not actually being used for some reason or another causing various assimp-related trouble
+ I have a nearly-finished build on Ubuntu 19.10 Eoan Ermine, only it outputs `ERROR: Framebuffer incomplete, GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT.` both with and without `LIBGL_ALWAYS_SOFTWARE=1`. Given that the Steam Windows build works fine under Proton, my guess is, something broke. No clue what, no way to find out.

**Comment by panmarco83** [comment]
I know, I am sorry about this, it has been fixed in my pull request.
There are multiple fixes in the works.

**Comment by panmarco83** [comment]
The build fixes are merged now, try cloning the repository again and run through the compile instructions in the README.md, it should go better now (?)
Also, there are options in the build script that you can list with --help

**Comment by 20kdc** [comment]
Definitely goes better. `git clone --recursive https://github.com/janusvr/janus` followed by `./build-janusvr-linux.sh -t 1` works just fine.
Using: Ubuntu 20.04.1 LTS (Focal Fossa)
Note that I still get: `ERROR: Framebuffer incomplete, GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT.`
This, however, is clearly unrelated to the build system.
So... building is fixed!
Thank you.
